#!/bin/bash


### sample input, -s seq, -m mutation lvl
#./script -s AGCGGGGGAGACAUAUAUCAUAGCCUGUCUCGUGCCCGACCCCGC -m 5 >> log.txt
#./script -s AGCGGGGGAGACAUAUAUCAUAGCCUGUCUCGUGCCCGACCCCGC -m 6 >> log.txt
#./script -s CCUUAACCAGCAAAAACUGCUGG -m 2 >> log.txt
#./script -s CCGGAAGAGGGGGACAACCCGGGGAAACUCGGGCUAAUCCCCCAUGUGGACCCGCCCCUUGGGGUGUGUCCAAAGGGCUUUGCCCGCUUCCGG -m 3 >> log.txt
#./script -s GGCAGUACCAAGUCUCAGGGGAAACUUUGAGAUGGCCUUGCAAAGGGUAUGGUAAUAAGCUGCC -m 2 >> log.txt
./script.py -s AGCGGGGGAGACAUAUAUCACAGCCUGUCUCGUGCCCGACCCCGC -m 2 >> e02.txt

