#!/bin/bash
echo ">wildtype"
cat result.txt | grep -i AGCGGGGGAGACAUAUAUCACAGCCUGUCUCGUGCCCGACCCCGC
echo ">A68C"
cat result.txt | grep -i AGCGGGGGAGACAUCUAUCACAGCCUGUCUCGUGCCCGACCCCGC
echo ">U71C"
cat result.txt | grep -i AGCGGGGGAGACAUAUACCACAGCCUGUCUCGUGCCCGACCCCGC
echo ">C74U"
cat result.txt | grep -i AGCGGGGGAGACAUAUAUCAUAGCCUGUCUCGUGCCCGACCCCGC
echo ">A75U_G76C_C77U"
cat result.txt | grep -i AGCGGGGGAGACAUAUAUCACUCUCUGUCUCGUGCCCGACCCCGC
echo ">C77U"
cat result.txt | grep -i AGCGGGGGAGACAUAUAUCACAGUCUGUCUCGUGCCCGACCCCGC
echo ">C84A_U86G"
cat result.txt | grep -i AGCGGGGGAGACAUAUAUCACAGCCUGUCUAGGGCCCGACCCCGC
echo ">C84A_U86A"
cat result.txt | grep -i AGCGGGGGAGACAUAUAUCACAGCCUGUCUAGAGCCCGACCCCGC
echo ">U86G"
cat result.txt | grep -i AGCGGGGGAGACAUAUAUCACAGCCUGUCUCGGGCCCGACCCCGC
echo ">C90A_A92G"
cat result.txt | grep -i AGCGGGGGAGACAUAUAUCACAGCCUGUCUCGUGCCAGGCCCCGC
echo ">C92G"
cat result.txt | grep -i AGCGGGGGAGACAUAUAUCACAGCCUGUCUCGUGCCCGGCCCCGC
echo ">C90A"
cat result.txt | grep -i AGCGGGGGAGACAUAUAUCACAGCCUGUCUCGUGCCAGACCCCGC
echo ">A92U"
cat result.txt | grep -i AGCGGGGGAGACAUAUAUCACAGCCUGUCUCGUGCCCGUCCCCGC
echo ">A92C"
cat result.txt | grep -i AGCGGGGGAGACAUAUAUCACAGCCUGUCUCGUGCCCGCCCCCGC

